### ISSUE TITLE
Constant and class with the same name can co-exist

### ISSUE THREAD

**Issue by ondrejmirtes** [shipmonk-rnd/name-collision-detector#19]
But name-collision-detector reports them as duplicate names. See: https://3v4l.org/qKq2s

**Comment by janedbal** [comment]
Thanks, I noticed that when [testing this library on phpstan-src](https://github.com/phpstan/phpstan-src/pull/2454), but I didnt finalize it yet. 

Just FYI, I plan to release 2.0 (major speed improvement) once it is fully usable for phpstan.
