### ISSUE TITLE
Ability to exclude files

### ISSUE THREAD

**Issue by ondrejmirtes** [shipmonk-rnd/name-collision-detector#20]
Somtimes there are duplicate names on purpose. It'd be great to exclude files from analysed directories. Similarly to what PHP-Parallel-Lint allows: https://github.com/php-parallel-lint/PHP-Parallel-Lint#command-line-options

**Comment by janedbal** [comment]
My idea was to use some config file to allow more possible options: https://github.com/shipmonk-rnd/name-collision-detector/pull/15/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R30

**Comment by ondrejmirtes** [comment]
Yes, it works now 🎉 https://github.com/phpstan/phpstan-src/commit/95cdbe577513286c36dcf513fe76f269e8a32125
